// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArvr8dWJmXqt3QyWsYJCRySOtihz_90q0',
    appId: '1:697992473958:web:f9a469a009c0d75faeeca7',
    messagingSenderId: '697992473958',
    projectId: 'telemed-19ed7',
    authDomain: 'telemed-19ed7.firebaseapp.com',
    storageBucket: 'telemed-19ed7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACdxQnv0XzsRMg44HGyaeIobVtXc1kj8I',
    appId: '1:697992473958:android:c492e68e0bc17595aeeca7',
    messagingSenderId: '697992473958',
    projectId: 'telemed-19ed7',
    storageBucket: 'telemed-19ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCya8SH9nfsbgCYf_A1UZEEUgn569iDy7I',
    appId: '1:697992473958:ios:c17b5ef6c926d789aeeca7',
    messagingSenderId: '697992473958',
    projectId: 'telemed-19ed7',
    storageBucket: 'telemed-19ed7.appspot.com',
    iosBundleId: 'com.example.telemed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCya8SH9nfsbgCYf_A1UZEEUgn569iDy7I',
    appId: '1:697992473958:ios:3211e08ca753c868aeeca7',
    messagingSenderId: '697992473958',
    projectId: 'telemed-19ed7',
    storageBucket: 'telemed-19ed7.appspot.com',
    iosBundleId: 'com.example.telemed.RunnerTests',
  );
}
